account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as account_views


app_name = "account"

urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', account_views.custom_logout_view, name='logout'),
    path('', account_views.dashboard, name='dashboard'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html'), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    path('register/', account_views.register, name='register'),
    path('verify/<email>/', account_views.verify, name='verify'),
    # path('edit-profile/', account_views.edit_profile, name='edit-profile'),
]

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- <link href="{% static 'css/base.css' %}" rel="stylesheet"> -->
    <!-- Development -->
    <!-- <script src="https://kit.fontawesome.com/6e865f5ab0.js" crossorigin="anonymous"></script> -->
    <script src="{% static 'fontawesome/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesome/js/solid.js' %}"></script>

    {% block links %}
    {% endblock %}
  
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">PCheck</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" 
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.app_name == 'account' and request.resolver_match.url_name == 'dashboard' %}active text-warning{% endif %}" 
                href="{% url 'account:dashboard' %}">
                Home
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.app_name == 'main_app' and request.resolver_match.url_name == 'pc-list' %}active text-warning{% endif %}" 
                href="{% url 'main_app:pc-list' %}">
                PCs
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Booking</a>
            </li>
          </ul>

          <!-- Right-aligned items -->
          <ul class="navbar-nav ms-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ request.user.first_name|default:request.user.username }}&nbsp;
              </a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'account:password_change' %}">Change password</a></li>
                <li><a class="nav-link" href="{% url 'account:logout' %}">Logout</a></li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% if messages %}
    <!-- Message Container -->
    <div id="message-container" 
      style="position: fixed; top: 70px; width: 100%; z-index: 9999; display: flex; 
            justify-content: center;">
        <div class="container">
          {% for message in messages %}
          <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show text-center" 
            role="alert" style="box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div id="content">
      {% block content %}
      {% endblock %}
    </div>

      {% block scripts %}
      {% endblock %}

    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script> -->
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script>
      setTimeout(function () {
        var alerts = document.querySelectorAll('.alert');
        alerts.forEach(function(alert) {
          // For Bootstrap 5: fade out then remove
          alert.classList.remove('show');
          alert.classList.add('fade');
          setTimeout(function () {
            alert.remove();
          }, 500); // wait for fade transition
        });
      }, 3000); // 3000 ms = 3 seconds
    </script>
  </body>
</html>