main_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main_app'

urlpatterns = [
    path('add-pc/', views.add_pc, name='add-pc'),
    path('delete-pc/<int:pk>/', views.delete_pc, name='delete-pc'),
    path('add-pc-from-form/', views.add_pc_from_form, name='add-pc-from-form'),
    path('pc-list/', views.PCListView.as_view(), name='pc-list'),
    path('pc-detail/<int:pk>/', views.PCDetailView.as_view(), name='pc-detail'),
    path('pc-update/<int:pk>/', views.PCUpdateView.as_view(), name='pc-update'),
    path('ping-ip/<int:pk>/', views.ping_ip_address, name='ping-ip'),
    path('ajax/get-ping-data/', views.get_ping_data, name='get-ping-data'),
    path('ajax/verify-pc-name/', views.verify_pc_name, name='verify-pc-name'),
    path('ajax/verify-pc-ip-address/', views.verify_pc_ip_address, name='verify-pc-ip-address'),
    path('ajax/get-pc-details/<int:pk>/', views.get_pc_details, name='get-pc-details'),
]

main_app/templates/main/add_pc.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Add PC{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="card mt-5 col-md-6">
    <div class="card-header text-center">
      <h2>Add PC</h2>
    </div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Submit</button>
        <a href="{% url 'main_app:pc-list' %}" class="btn btn-secondary">Cancel</a>
      </form>
    </div>    
  <div>
</div>
{% endblock %}

main_app/templates/main/pc_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PC detail{% endblock %}

{% block content %}
<div class="container col-md-4">
  <div class="header text-center mt-5">
    <h2>PC Detail View</h2>
  </div>
  <div class="table-responsive">
    <table class="table table-bordered table-condensed table-sm mt-3">
      <thead>
        <tr>
          <th>Field</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="bg-light">Name</td>
          <td>{{ pc.name }}</td>
        </tr>
        <tr>
          <td class="bg-light">IP Address</td>
          <td>{{ pc.ip_address }}</td>
        </tr>
        <tr>
          <td class="bg-light">Status</td>
          <td>{{ pc.status }}</td>
        </tr>
        <tr>
          <td class="bg-light">Health</td>
          <td>{{ pc.health }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="mt-3">
    <a href="{% url 'main_app:pc-update' pk=pc.pk %}" class="btn btn-warning">edit</a>
    <a href="{% url 'main_app:delete-pc' pk=pc.pk %}" class="btn btn-danger">delete</a>
  </div>
</div>
{% endblock %}

main_app/templates/main/pc_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PC List{% endblock %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
<!-- <style>
  .loader {
    border: 6px solid #f3f3f3; /* Light gray */
    border-top: 6px solid #3498db; /* Blue */
    border-radius: 50%;
    width: 40px;
    height: 40px;
    animation: spin 1s linear infinite;
    margin: auto;
  }
  
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }

  .menu-button {
    border: 1px solid #ccc;
    border-radius: 5px;
    background: none;
    padding: 0.5em 1em;
    cursor: pointer;
    margin-bottom: 1em;
    color: black;
  }
</style> -->
{% endblock %}

{% block content %}
<div class="container">

  <div class="text-center mt-3 mb-3">
    <h1>PC List</h1>
  </div>

  <div class="row">

    <!-- Left Column -->
    <div class="col-md-3 col-sm-4 mt-3">
      <div class="card h-100">
        <div class="card-header text-center">
          <button id="addPCbutton" class="btn btn-round btn-secondary shadow menu-button mb-2">
            Add PC
          </button>
          <br>
          <a href="{% url 'main_app:pc-list' %}?filter=repair" 
            id="repair-button" class="btn btn-round btn-secondary shadow menu-button mb-2">
            Repair
          </a>
        </div>

        <div class="card-body" id="PCformDiv" hidden>
          <h5 id="form-title">Add a PC</h5>
          <form method="post" id="pc-form">
            {% csrf_token %}
            <input type="hidden" name="pc_id" id="pc_id">
            <div class="form-group mt-3">
              {{form.name.errors}}
              {{form.name.label_tag}}
              {{form.name}}
              <span class="text-danger" id="name-error"></span>
            </div>
            <div class="form-group mt-3">
              {{form.ip_address.errors}}
              {{form.ip_address.label_tag}}
              {{form.ip_address}}
              <span class="text-danger" id="ip-address-error"></span>
            </div>
            <div class="form-group mt-3" hidden>
              {{form.status.errors}}
              {{form.status.label_tag}}
              {{form.status}}
            </div>
            <div class="mt-3">
              <p class="mt-1">Status: <span id="status_indicator"></span></p>
              <div id="spinner" style="display: none; text-align:center; margin-top:20px;">
                <div class="loader"></div>
                <p>Connecting...</p>
              </div>
              <button type="button" id="connectButton" class="btn btn-sm btn-secondary">Connect</button>
            </div>
            <div class="form-group mt-3">
              {{form.system_condition.errors}}
              {{form.system_condition.label_tag}}
              {{form.system_condition}}
            </div>
            <div class="mt-3">
              <button type="submit" class="btn btn-sm btn-primary" id="save-button">Save</button>
              <button type="button" id="cancel-button" style="display:none;" class="btn btn-sm btn-secondary">Cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- Right Column -->
    <div class="col-md-9 col-sm-8 mt-3">
      <div class="card">
        <div class="card-body">
          <table class="table table-striped table-hover table-sm">
            <thead class="thead-dark">
              <tr>
                <th>PCs</th>
                <th>IP Address</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for pc in pc_list %}
              <tr class="edit-row" data-pc-id="{{ pc.pk }}" data-name="{{ pc.name }}" 
                data-ip="{{ pc.ip_address }}" data-status="{{ pc.status }}" data-health="{{ pc.system_condition }}">
                <td>{{ pc.name }}</td>
                <td>{{ pc.ip_address }}</td>
                <td>
                  {% if pc.status == 'connected' %}
                    <i class="fa-solid fa-circle text-success"></i>
                  {% else %}
                    <i class="fa-solid fa-circle text-danger"></i>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'main_app:pc-update' pk=pc.pk %}" class="btn" title="edit PC">
                    <i class="fa-solid fa-user-pen"></i>
                  </a>
                  <a class="btn" href="{% url 'main_app:delete-pc' pk=pc.pk %}" title="delete PC">
                    <i class="fa-solid fa-trash"></i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>


{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'js/myscript.js' %}"></script>
{% endblock %}

main_app/templates/main/ping_address.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ping IP{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="col-md-4">
    <div class="card mt-5">
      <div class="card-header text-center">
        <h2>Ping IP</h2>
      </div>
      <div class="card-body {% if result %}bg-success text-white{% else %}bg-danger text-white{% endif %}">
        <p>IP Address: {{ ip_address }}</p>
        <p>Status: {{ result|yesno:"Reachable,Unreachable" }}</p>
        <a href="{% url 'main_app:pc-list' %}" class="btn btn-secondary">Back to List</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main/update_pc.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Update PC{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
  <div class="card mt-5 col-md-6">
    <div class="card-header text-center">
      <h2>Update PC</h2>
    </div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Submit</button>
        <a href="{% url 'main_app:pc-detail' pk=pc.pk %}" class="btn btn-secondary">Reset</a>
      </form>
    </div>    
  <div>
</div>
{% endblock %}